---
title: "Daily Log"
author: "j-shangguan"
date: "2021-01-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Week 1: Jan. 11-15

* Project planning
    + Reading literature 
    + Detailed rotation project outline 

## Week 2: Microscope set-up training
### 1.17.21 
* Aligning the laser 
    + prism in front of diode laser
    + lens 
        - focal length
        - collimated beam of light (parallel rays in beam) vs. converging to a focus 
            - collimated: focused at infinity; place lens focal length distance away from source
            - if collimated light enter a lens, it focuses one focal length distance away 
        - confocal vs widefield setup 
        - adding magnification 

### 1.18.21 
* Aligning the laser continued
    + adding mirrors to direct beam into microscope
    + adjusting mirrors to center light path and make beam symmetric 
    + using irises to check along light path
    + checking backscatter of light for each lens in path
    + added filters to path 
* Drummond lab meeting: Jared's research
* Squires lab meeting: Kyle's research proposal/interests

### 1.19.21
* Setting up the camera
  + added Kohler lens for widefield microscopy
  + directed light from microscope side port into camera 
  + detected blinking from Sharpie-marked coverslips
* Meeting with Allan and Allison about my rotation project outline/research plans 
  
### 1.20.21
* Setting up the camera
  + readjust Kohler lens and lens paths to camera, readjust camera 
* Imaged Ranchi ruler to get pixel size  
* Learned how to use plasma etcher to clean glass slides
* Calculations
  + calculating Raleigh scattering and filters needed to attenuate power
  + calculating Raman scattering 

### 1.21.21
* Used UV-Vis to take absorbance data on filters 
    + longpass, emission
    + bandpass
    + excitation

### 1.22.21
* Made fraction of emitted fluorescence spectrum 

### 1.24.21
* Imaged sharpie sample
* Worked on beam intensity calculation
* Worked on gain conversion calculation

## Week 3: Microscope Training Data Analysis, Rotation Project Material Prep

### 1.25.21
* Took videos with different white light intensities (for gain calculation)
* Worked on beam intensity calculation
* Worked on ppt outline
* Drummond lab meeting: Hendrik's research
* Squires lab meeting: Jiachong's qual practice

### 1.26. 21 
* Finished beam intensity calculation 
* Worked on ppt outline

### 1.27.21
* Trained on new Nanodrop 
* Worked on gain conversion calculation

### 1.28.21
* Worked on ppt outline

### 1.29.21
* Made aggregation buffer
* Imaged blinking sample at 10x-3 from 10 nM dilution Cy3-DNA on PVA coated coverslip
* Allison realigned laser path  
* Worked on particle fitting code 
* Worked on ppt outline

### 1.30.21
* Heat shocked 1:20 Pab1-mRuby2 in unlabeled Pab1 solution (total ~25 uM condensates); imaged
* Worked on ppt outline

### 1.31.21
* Worked on ppt outline

## Week 3: Microscope Training Data Analysis, Rotation Project Initial Tests

### 2.1.21
* I presented on my rotation project proposal

### 2.2.21
* Worked on particle fitting code

### 2.3.21
* Worked on photon calculation code 
* Heat shocked Apa1-mRuby2 (2 uM condensate); imaged

### 2.4.21
* Measured size of Apa1 and Pab1 condensates
* Summarized data, planning next steps 
