---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Welcome to my winter quarter rotation documentation website.

### Get up to speed on the biological context of my project

**Here are general misc. notes and information relevant to this project:** [background info](notes.html)
* Methods for studying condensates: [studying_condensates.html]

**Here are helpful articles and notes to get background info:** [literature review](literature.html)
* Specifically about Nug1: [Nug1 info](nug1.html)


### Take a peek at my project progress

**Here are my experimental plans**: [plans](nextsteps.html)

**This is what I'm up to:** [activity log](dailylog.html)

**Data:** (set up webpage)

### Goals of my rotation project:

* Understanding formation and function of biomolecular condensates
* Investigating and visualizing protein organization within heat shock-induced condensates
* Learning imaging approaches to probe the specificity of assembly of heat shock-induced condensates; training will include microscope set-up, protein labeling and potential single-molecule imaging techniques 
